<?xml version="1.0" ?>

<robot name="stand" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:arg name="gazebo" default="false"/>
    <xacro:if value="$(arg gazebo)">
        <!-- Gazebo Tags -->
        <xacro:include filename="$(find kinect_description)/urdf/stand/stand.gazebo.xacro"/>
    </xacro:if>
    <xacro:include filename="$(find kinect_description)/urdf/stand/properties.xacro"/>
    <xacro:include filename="$(find kinect_description)/urdf/stand/materials.xacro"/>
    <xacro:include filename="$(find kinect_description)/urdf/stand/macros.xacro"/>

    <link name="footprint"/>

    <joint name="base_joint" type="fixed">
        <parent link="footprint"/>
        <child link="foot"/>
    </joint>

    <link name="foot">
        <visual>
            <origin xyz="0 0 ${footHeight/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${footHeight}" radius="${footRadius}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0 0 ${footHeight/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${footHeight}" radius="${footRadius}"/>
            </geometry>
            <contact_coefficients mu="0" kp="1000.0" kd="1.0"/>
        </collision>
        <inertial>
            <mass value="${footMass}"/>
            <cylinder_inertia m="${footMass}"
                              r="${footRadius}" h="${footHeight}"/>
        </inertial>
    </link>

    <joint name="foot_joint" type="fixed">
        <parent link="foot"/>
        <child link="stand"/>
        <origin xyz="0 0 ${footHeight}" rpy="0 0 0"/>
    </joint>

    <link name="stand">
        <visual>
            <origin xyz="0 0 ${standHeight/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${standHeight}" radius="${standRadius}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0 0 ${footHeight/2+standHeight/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${standHeight}" radius="${standRadius}"/>
            </geometry>
            <contact_coefficients mu="0" kp="1000.0" kd="1.0"/>
        </collision>
        <inertial>
            <mass value="${standMass}"/>
            <cylinder_inertia m="${standMass}"
                              r="${standRadius}" h="${standHeight}"/>
        </inertial>
    </link>

    <joint name="sensor_joint" type="fixed">
        <parent link="stand"/>
        <child link="sensor_link"/>
        <origin xyz="0 0 ${footHeight+standHeight}" rpy="0 0 ${PI}"/>
    </joint>

    <link name="sensor_link"/>
</robot>